# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: ultralytics_yolo_example
description: "Demonstrates how to use the ultralytics_yolo plugin."
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10
  image_picker: ^0.8.7
  gal: ^2.3.0
  path_provider: ^2.0.0
  archive: ^3.0.0
  http: ^1.0.0
  permission_handler: ^11.3.1

  ultralytics_yolo:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
    - assets/logo.png
    - assets/applogo.png
    - lib/assets/app-logo.png
    - lib/assets/app-logo-dark.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app-logo.png"

flutter_native_splash:
  color: "#F7F8F7"
  image: lib/assets/app-logo.png
  branding: lib/assets/app-logo.png
  color_dark: "#0F1110"
  image_dark: lib/assets/app-logo-dark.png
  branding_dark: lib/assets/app-logo-dark.png
  android_12:
    image: lib/assets/app-logo.png
    color: "#F7F8F7"
    image_dark: lib/assets/app-logo-dark.png
    color_dark: "#0F1110"
    icon_background_color: "#F7F8F7"
    icon_background_color_dark: "#0F1110"
